"""reason of blocking

Revision ID: 3e476675d184
Revises: c3bc99706d3c
Create Date: 2024-07-23 17:31:05.647546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e476675d184'
down_revision: Union[str, None] = 'c3bc99706d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('block_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'block_reason')
    # ### end Alembic commands ###
