"""response_on_comment field

Revision ID: 5ed2d3869ce5
Revises: b087475f29f2
Create Date: 2024-07-28 15:06:02.313795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed2d3869ce5'
down_revision: Union[str, None] = 'b087475f29f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('response_on_comment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['response_on_comment'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'response_on_comment')
    # ### end Alembic commands ###
