"""blocked, block_reason for Post table

Revision ID: 94be5973de84
Revises: 5ed2d3869ce5
Create Date: 2024-07-28 16:59:17.928566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94be5973de84'
down_revision: Union[str, None] = '5ed2d3869ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blocked', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('block_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'block_reason')
    op.drop_column('posts', 'blocked')
    # ### end Alembic commands ###
