"""response_interval

Revision ID: b087475f29f2
Revises: 8fff49cfeee9
Create Date: 2024-07-28 13:45:27.361265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b087475f29f2'
down_revision: Union[str, None] = '8fff49cfeee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('response_interval', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'response_interval')
    # ### end Alembic commands ###
