"""blocked comment or not

Revision ID: c3bc99706d3c
Revises: d9f60809d632
Create Date: 2024-07-23 17:22:30.825543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bc99706d3c'
down_revision: Union[str, None] = 'd9f60809d632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'blocked')
    # ### end Alembic commands ###
