"""no photo

Revision ID: f783a413a8b8
Revises: 80b4b7002b5f
Create Date: 2024-07-25 18:45:54.052111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f783a413a8b8'
down_revision: Union[str, None] = '80b4b7002b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photo')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
